// ─── reCAPTCHA Enterprise Server-Side Verification ─────────────────────────
// Verifies tokens generated by the reCAPTCHA Enterprise JS library.
// Docs: https://cloud.google.com/recaptcha-enterprise/docs/create-assessment

const RECAPTCHA_PROJECT_ID = process.env.RECAPTCHA_PROJECT_ID || "civil-clarity-504700-k9";
const RECAPTCHA_SITE_KEY   = process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY || "6LchenctAAAAAHpLKDsK-Igil1E3rCXzI8J2DqzC";
const RECAPTCHA_API_KEY    = process.env.RECAPTCHA_API_KEY; // Google Cloud API Key

/**
 * Verifies a reCAPTCHA Enterprise token and returns the risk score.
 * Score: 1.0 = very likely human, 0.0 = very likely bot.
 * Returns null if verification fails or API key is missing.
 */
export async function verifyRecaptcha(token: string, expectedAction: string): Promise<number | null> {
  if (!RECAPTCHA_API_KEY) {
    console.warn("[reCAPTCHA] ⚠️ RECAPTCHA_API_KEY not set — skipping verification");
    return 0.9; // Allow in dev if no key is set
  }

  if (!token) return 0;

  try {
    const url = `https://recaptchaenterprise.googleapis.com/v1/projects/${RECAPTCHA_PROJECT_ID}/assessments?key=${RECAPTCHA_API_KEY}`;

    const response = await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        event: {
          token,
          expectedAction,
          siteKey: RECAPTCHA_SITE_KEY,
        },
      }),
    });

    if (!response.ok) {
      console.error("[reCAPTCHA] API error:", response.status, await response.text());
      return null;
    }

    const data = await response.json();

    // Check that the action matches
    if (data.tokenProperties?.action !== expectedAction) {
      console.warn(`[reCAPTCHA] Action mismatch: expected "${expectedAction}", got "${data.tokenProperties?.action}"`);
      return 0;
    }

    if (!data.tokenProperties?.valid) {
      console.warn("[reCAPTCHA] Invalid token:", data.tokenProperties?.invalidReason);
      return 0;
    }

    const score = data.riskAnalysis?.score ?? 0;
    console.log(`[reCAPTCHA] Score for action "${expectedAction}": ${score}`);
    return score;

  } catch (err: any) {
    console.error("[reCAPTCHA] Verification error:", err.message);
    return null;
  }
}

/**
 * Returns true if the request is likely from a human.
 * Threshold: score >= 0.5 (Google recommends 0.5 as a balanced threshold).
 */
export async function isHuman(token: string, action: string, threshold = 0.5): Promise<boolean> {
  const score = await verifyRecaptcha(token, action);
  if (score === null) return false; // API error — reject to be safe
  return score >= threshold;
}
